### ISSUE TITLE
Feature Request: Zeit in der Fortschrittsanzeige des Koalitionstrackers

### ISSUE THREAD

**Issue by MaxMatti** [okfde/froide-govplan#4]
Hi, vielen Dank für den Koalitionstracker! Es wäre aber super, in dem Balken sehen zu können wie viel der Zeit dieser Legislaturperiode bereits vergangen ist, um einen Vergleich zu haben.

zB so:
![image](https://user-images.githubusercontent.com/1584478/159887805-4eaa289b-b578-4271-8f97-524b36ef192d.png)

**Comment by stefanw** [comment]
Gibt's jetzt, aber als separater Fortschritts-Balken umgesetzt.
