### ISSUE TITLE
Regierung und Vorhaben hinzugefügt, aber Webseite bleibt leer

### ISSUE THREAD

**Issue by RodBelaFarin** [okfde/froide-govplan#9]
Ich habe den Server mit Hilfe der README.md erfolgreich aufgesetzt und die folgenden Schritte befolgt, um Vorhaben zu erzeugen:

1. Go to http://localhost:8000/admin/
2. Setup a homepage in the CMS: http://localhost:8000/admin/cms/page/
3. Setup a page (could be the homepage) and then choose under advanced setting the Govplan app as application.
4. Publish that page
5. Setup a government and plans via the admin.

Ich habe eine Homepage angelegt und in den erweiterten Einstellungen die "Govplan app" als Anwendung hinzugefügt und danach die Seite veröffentlicht. Anschließend habe ich in den Govplan App Einstellungen eine Regierung und zunächst testweise zwei Vorhaben hinzugefügt.

Beim Aufruf der Homepage bleibt der Seiteninhalt allerdings leer. Muss ich noch etwas tun, damit die Vorhaben auf der Homepage angezeigt werden?

**Comment by stefanw** [comment]
Es gibt ein `public`-Flag auf der "Regierung" und den Vorhaben. Sind die angehakt?

**Comment by RodBelaFarin** [comment]
Ja, beide Vorhaben sind `public`. Wird in der Vorschau in den Einstellungen mit grünem Haken bestätigt.

**Comment by stefanw** [comment]
Ah, der Root-Path der app hat keine eigene View. Stattdessen können dort CMS Plugins eingesetzt werden, die Regierungsvorhaben oder Regierungsvorhaben-Themenbereiche anzeigen.

Im Admin sollten sich aber die Vorhaben oder Themenbereiche-Seiten über "Auf Webseite anzeigen" auch direkt aufrufen lassen.

**Comment by RodBelaFarin** [comment]
Habe eine `test_page` angelegt, um das Problem mit dem Root-Verzeichnis zu umgehen.

![image](https://github.com/okfde/froide-govplan/assets/4102884/6cbcf4bb-ec01-498d-add6-a89535562d66)
Dann hier? Oder auf einer anderen Ansicht?

Über das Auge werde ich auf die Unterseite /test_page weitergeleitet und sehe aber wieder nur eine leere weiße Seite :(

**Comment by stefanw** [comment]
Die Seite ist eine Django-CMS-Seite, die kannst du also bearbeiten und dann Plugins in den Placeholder hinzufügen, die die GovPlan-Datenbank-Objekte anzeigen. Funktioniert denn das Aufrufen der Vorhaben über den Admin direkt?

**Comment by RodBelaFarin** [comment]
> Funktioniert denn das Aufrufen der Vorhaben über den Admin direkt?

Genau diese Möglichkeit finde ich bei mir leider nicht. Wahrscheinlich übersehe ich etwas.

**Comment by stefanw** [comment]
<img width="1063" alt="Screenshot 2023-09-01 at 14 32 18" src="https://github.com/okfde/froide-govplan/assets/78356/72eb4144-def8-4d59-b4c8-1ee9619fec3d">

So sieht das bei mir aus. Damit das besser aussieht, muss die App in einem separaten Django-Projekt eingebaut werden mit eigenen Base-Templates.

**Comment by RodBelaFarin** [comment]
Ah! Oben rechts kann man aufklappen! Ich wusste doch, dass ich etwas übersehe.

Das war's. Danke, top! Dann schaue ich mir jetzt an, wie das mit den Templates funktioniert, damit ich auch so einen wunderschönen Tracker bauen kann, wie den Koalitationstracker. Tolle Arbeit!

**Comment by onny** [comment]
@stefanw @RodBelaFarin ist es möglich das bestehende template vom koalitionstracker zu übernehmen und anzupassen oder muss ein komplett neues template from scratch geschrieben werden?

**Comment by RodBelaFarin** [comment]
> @stefanw @RodBelaFarin ist es möglich das bestehende template vom koalitionstracker zu übernehmen und anzupassen oder muss ein komplett neues template from scratch geschrieben werden?

Die Möglichkeit habe ich zumindest nicht gefunden. Ich habe selbst ein neues Template gebastelt.

**Comment by stefanw** [comment]
Es gibt leider kein default template, gerne kannst du eins vorschlagen. Wir haben nur das allgemeine FDS-Template, aber das ist natürlich nicht in diesem Repo.
